In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
station_data = pd.read_csv("/Users/robstallman/Downloads/Station_Data_Extract_Pipe_Delimited_CleanData_2021.txt", delimiter="|")
el_paso_stations = ["00A123", "00S162", "00A189", "2402", "000S70"]
station_data.loc[station_data['Station_Id'].isin(el_paso_stations)]

/var/folders/7m/3r23lm6s517bl9502bgqp64w0000gn/T/ipykernel_82931/3742981299.py:1: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  station_data = pd.read_csv("/Users/robstallman/Downloads/Station_Data_Extract_Pipe_Delimited_CleanData_2021.txt", delimiter="|")

,Record_Type,State_Code,Station_Id,Travel_Dir,Travel_Lane,Year_Record,F_System,Num_Lanes,Sample_Type_Volume,Num_Lanes_Volume,...,Year_Discontinued,County_Code,Is_Sample,Sample_Id,NHS,Posted_Route_Signing,Posted_Signed_Route,Con_Route_Signing,Con_Signed_Route,Station_Location
24556,S,48,00A123,3,0,21,1U,2,T,2,...,,141,Y,000000003290,Y,1,00000010,0,,"IH 10, 0.4 MILE EAST OF LOOP 375 ..."
25540,S,48,00A123,7,0,21,1U,2,T,2,...,,141,Y,000000003290,Y,1,00000010,0,,"IH 10, 0.4 MILE EAST OF LOOP 375 ..."
25562,S,48,00A189,5,0,21,3R,4,T,4,...,,141,N,,Y,2,00000054,0,,0.4 MILE NORTH OF IH 10 ...
25629,S,48,00A189,1,0,21,3R,4,T,4,...,,141,N,,Y,2,00000054,0,,0.4 MILE NORTH OF IH 10 ...

In [9]:
counts = pd.read_csv('/Users/robstallman/Downloads/jan_2021_ccs_data/TX_JAN_2021 (TMAS).VOL', delimiter='|')
counts.loc[counts['station_id'].isin(el_paso_stations)]

,record_type,state_code,f_system,station_id,travel_dir,travel_lane,year_record,month_record,day_record,day_of_week,...,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,restrictions
12772,3,48,1U,00A123,3,0,21,1,1,6,...,1963,2016,1980,1898,1648,1242,890,673,530,0
12773,3,48,1U,00A123,3,0,21,1,2,7,...,2354,2544,2375,2500,2038,1628,1098,879,665,0
12774,3,48,1U,00A123,3,0,21,1,3,1,...,2275,2393,2257,2074,1704,1246,850,687,519,0
12775,3,48,1U,00A123,3,0,21,1,4,2,...,2190,2548,2521,2639,1907,1269,814,626,453,0
12776,3,48,1U,00A123,3,0,21,1,5,3,...,2304,2668,2735,2812,1991,1433,886,699,500,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13037,3,48,3R,00A189,5,0,21,1,25,2,...,2185,2277,2006,1401,918,330,10,1,0,0
13038,3,48,3R,00A189,5,0,21,1,26,3,...,2220,2458,2006,1693,1195,606,484,348,255,0
13039,3,48,3R,00A189,5,0,21,1,28,5,...,2260,2477,2064,1531,1029,450,17,4,1,0
13040,3,48,3R,00A189,5,0,21,1,30,7,...,1964,1847,1749,1602,1123,814,691,551,399,0
13041,3,48,3R,00A189,5,0,21,1,31,1,...,1619,1500,1377,1042,838,646,538,466,465,0